baseURL = "https://jaceys.me"
title = "Jaceys | Photography & Travel"
theme = "stardust"
paginate = 20

[params]
description = """Jaceys - Freelance travel photographer based in the UK, dedicated to capturing moments based around landscapes, lifestyle and adventure."""
copyright = "Jaceys"

  [[params.social]]
  name = "email"
  href = "mailto:jaceys.tan@gmail.com"
  ionicon = "mail"

  [[params.social]]
  name = "instagram"
  href = "https://instagram.com/jaceys_"
  ionicon = "logo-instagram"

[menu]
  [[menu.nav]]
  identifier = "stills"
  name = "Stills"
  url = "/"
  weight = "1"

  [[menu.nav]]
  identifier = "videos"
  name = "Videos"
  url = "/videos/"
  weight = "2"

  [[menu.nav]]
  identifier = "portfolio"
  name = "Portfolio"
  url = "/portfolio/"
  weight = "3"

  [[menu.nav]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = "4"

  [[menu.nav]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = "5"

  [[menu.nav]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = "6"
