---
site_url: https://jaceystan.com
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

backend:
  name: git-gateway
  squash_merges: true

local_backend: true

editor:
  preview: false

media_library:
  name: cloudinary
  config:
    cloud_name: jaceystan
    api_key: 634315473442474

collections:
  - label: "Config"
    name: "config"
    format: "toml"
    files:
      - label: "Hugo"
        name: "hugo"
        file: "config.toml"
        fields:
          - { label: "URL", name: "baseURL", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Params",
              name: "params",
              widget: "object",
              fields:
                [
                  { label: "Description", name: "description", widget: "text" },
                  { label: "Copyright", name: "copyright", widget: "string" },
                  {
                    label: "Social",
                    name: "social",
                    widget: "list",
                    collapsed: false,
                    allow_add: true,
                    fields:
                      [
                        { label: "Name", name: "name", widget: "string" },
                        { label: "Href", name: "href", widget: "string" },
                        { label: "Text", name: "text", widget: "string" },
                        { label: "Ionicon", name: "ionicon", widget: "string" },
                      ],
                  },
                ],
            }

  - label: "Sections"
    name: "sections"
    format: "toml-frontmatter"
    files:
      - label: "Home"
        name: "home"
        file: "content/stills/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Headline", name: "headline", widget: "string" }
          - {
              label: "Typed",
              name: "typed",
              widget: "list",
              collapsed: false,
              allow_add: true,
              field: { label: "Title", name: "title", widget: "string" },
            }

      - label: "Portfolio"
        name: "portfolio"
        file: "content/portfolio/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

      - label: "Videos"
        name: "videos"
        file: "content/videos/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

      - label: "Blog"
        name: "blog"
        file: "content/blog/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

      - label: "About"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Image",
              name: "image",
              widget: "image",
              choose_url: false,
            }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Contact"
        name: "contact"
        file: "content/contact/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Location", name: "location", widget: "string" }

  - label: "Stills"
    name: "stills"
    format: "toml-frontmatter"
    folder: "content/stills"
    preview_path: "stills/{{slug}}"
    filter: { field: "collection", value: true }
    nested:
      depth: 2
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          time_format: false,
          picker_utc: true,
        }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          choose_url: false,
        }
      - { label: "Collection", name: "collection", widget: "hidden", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Videos"
    name: "videos"
    format: "toml-frontmatter"
    folder: "content/videos"
    preview_path: "videos"
    filter: { field: "collection", value: true }
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          time_format: false,
          picker_utc: true,
        }
      - { label: "Collection", name: "collection", widget: "hidden", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Portfolio"
    name: "portfolio"
    format: "toml-frontmatter"
    folder: "content/portfolio"
    preview_path: "portfolio/{{slug}}"
    filter: { field: "collection", value: true }
    nested:
      depth: 2
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          time_format: false,
          picker_utc: true,
        }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          choose_url: false,
        }
      - { label: "Collection", name: "collection", widget: "hidden", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Blog"
    name: "blog"
    format: "toml-frontmatter"
    folder: "content/blog"
    preview_path: "blog/{{slug}}"
    filter: { field: "collection", value: true }
    nested:
      depth: 2
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          time_format: false,
          picker_utc: true,
        }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          choose_url: false,
        }
      - {
          label: "Metadata",
          name: "metadata",
          widget: "object",
          fields:
            [
              {
                label: "Author",
                name: "author",
                widget: "string",
                default: "Jace Tan",
              },
            ],
        }
      - { label: "Collection", name: "collection", widget: "hidden", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
